path_classifiers:
  test:
    - "*/*/*_test.hpp"
    - "tests/gx-test-main.cpp"
#  docs:

queries:
#  - exclude: cpp/use-of-goto

extraction:
  cpp:
    prepare:
      packages:
        - wget
    after_prepare:
      - mkdir build
      - cd build
      - export CMAKE_VER="3.19.2"
      - wget "https://github.com/Kitware/CMake/releases/download/v${CMAKE_VER}/cmake-${CMAKE_VER}-Linux-x86_64.tar.gz"
      - tar -xf "cmake-${CMAKE_VER}-Linux-x86_64.tar.gz"
      - ls
      - rm "cmake-${CMAKE_VER}-Linux-x86_64.tar.gz"
      - export PATH="`pwd`/cmake-${CMAKE_VER}-Linux-x86_64/bin:${PATH}"
      - wget "https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.1/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10.tar.xz"
      - ls
      - tar -xf "clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10.tar.xz"
      - ls
      - mv "clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10.tar.xz" compiler
      - ls compiler/*
      - export CC="`pwd`/compiler/bin/clang-11"
      - export CXX="`pwd`/compiler/bin/clang++-11"
      - export PATH="`pwd`compiler/bin:${PATH}"
      - export CMAKE_BUILD_PARALLEL_LEVEL=16
    configure:
      command:
        - cd build
        - cmake ..
    index:
      build_command:
        - cd build
        - cmake --build . --config Release