path_classifiers:
  test:
    - "*/*/*_test.hpp"
    - "tests/gx-test-main.cpp"
#  docs:

queries:
#  - exclude: cpp/use-of-goto

extraction:
  cpp:
    prepare:
      packages:
        - wget
    after_prepare:
      - mkdir build
      - cd build
      - wget "https://github.com/Kitware/CMake/releases/download/v3.19.2/cmake-3.19.2-Linux-x86_64.tar.gz"
      - tar -xf "cmake-3.19.2-Linux-x86_64.tar.gz"
      - rm "cmake-3.19.2-Linux-x86_64.tar.gz"
      - mv "cmake-3.19.2-Linux-x86_64" custom_cmake
      - export PATH="`pwd`/custom_cmake/bin:${PATH}"
      - wget "https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.1/clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10.tar.xz"
      - tar -xf "clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10.tar.xz"
      - rm "clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10.tar.xz"
      - mv "clang+llvm-11.0.1-x86_64-linux-gnu-ubuntu-20.10" custom_clang
      - ls custom_clang
      - export CC="`pwd`/custom_clang/bin/clang-11"
      - export CXX="`pwd`/custom_clang/bin/clang++-11"
      - export PATH="`pwd`/custom_clang/bin:${PATH}"
      - export CMAKE_BUILD_PARALLEL_LEVEL=16
    configure:
      command:
        - cd build
        - cmake --version
        - cmake ..
    index:
      build_command:
        - cd build
        - cmake --version
        - cmake --build . --config Release