name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: sudo apt-get update
      - name: Install dependancies
        run: sudo apt-get install clang++-10 clang-10 wget
      - name: Echo places
        run: echo $HOME && echo `pwd`
      - name: Install CMake
        run: wget "https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4-Linux-x86_64.tar.gz" &&
          tar -xf cmake-3.18.4-Linux-x86_64.tar.gz && ls && rm cmake-3.18.4-Linux-x86_64.tar.gz &&
          export PATH="$HOME/cmake-3.18.4-Linux-x86_64/bin:$PATH"
      - name: Cmake version check
        run: cmake --version