name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: apt-get update
      - name: Upgrade
        run: apt-get dist-upgrade -y
      - name: Install dependancies
        run: apt-get install clang++-10 clang-10 wget
      - name: Install CMake
        run: wget "https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4-Linux-x86_64.tar.gz" &&
             tar x cmake-3.18.4-Linux-x86_64.tar.gz &&
             mv cmake* cmake &&
             export PATH="$HOME/cmake/bin:$PATH"
      - name: Cmake version check
        run: cmake --version
