name: Windows 2019 release build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Install CMake
        shell: powershell
        run: |
          Write-Host "GITHUB_PATH: $env:GITHUB_PATH"
          Write-Host "GITHUB_ENV: $env:GITHUB_ENV"
          Get-Content "$env:GITHUB_PATH"
          Get-Content "$env:GITHUB_ENV"
          New-Item -ItemType Directory -Force -Path build
          Set-Location -Path build
          $cmake_ver = "3.19.2"
          $cmake_address = "https://github.com/Kitware/CMake/releases/download/v${cmake_ver}/cmake-${cmake_ver}-win64-x64.zip"
          Write-Host "Going to download CMake from: ${cmake_address}."
          Invoke-WebRequest "${cmake_address}" -OutFile "cmake.zip"
          Write-Host "Going to uncompress the cmake.zip."
          Expand-Archive "cmake.zip" -DestinationPath "cmake"
          Write-Host "Going to delete cmake.zip."
          Remove-Item -Path "cmake.zip"
          Write-Host "Add cmake to PATH."
          Add-Content -Path "$env:GITHUB_PATH" -Value "$((Get-Item .).FullName)\cmake\cmake-${cmake_ver}-win64-x64\bin"
          Add-Content -Path "$env:GITHUB_ENV" -Value "CMAKE_BUILD_PARALLEL_LEVEL=$((Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors * 8)"
      - name: Install Vulkan SDK
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path build
          Set-Location -Path build
          Write-Host "Goint to download the latest Vulkan SDK."
          Invoke-WebRequest "https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe" -OutFile vulkan-sdk.exe
          Write-Host "Goint to install the Vulkan SDK."
          .\vulkan-sdk.exe /S
          Write-Host "Add Vulkan SDK to PATH."
          Dir C:\
          Dir C:\VulkanSDK
          Set-Location -Path "$((Get-ChildItem -Path "C:\VulkanSDK\*" | Select-Object -First 1).FullName)"
          Dir .
          Add-Content -Path "$env:GITHUB_PATH" -Value "$((Get-Item .).FullName)\Bin"
          Add-Content -Path "$env:GITHUB_ENV" -Value "VULKAN_SDK=$((Get-Item .).FullName)"
      - name: Echo settings
        shell: powershell
        run: |
          Write-Host "Vulkan SDK Path: $env:VULKAN_SDK"
          Write-Host "Path: $env:Path"
          Write-Host "CMake thread option: $env:CMAKE_BUILD_PARALLEL_LEVEL"
      - name: Realse build
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Path build
          Set-Location -Path build
          cmake ..
          cmake --build . --config Release