name: Windows 2019 release build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Install CMake
        shell: powershell
        run: |
          Write-Host "GITHUB_PATH: $env:GITHUB_PATH"
          Write-Host "GITHUB_ENV: $env:GITHUB_ENV"
          Get-Content "$env:GITHUB_PATH"
          Get-Content "$env:GITHUB_ENV"
          New-Item -ItemType Directory -Force -Path build
          Set-Location -Path build
          $cmake_ver = "3.19.2"
          Invoke-WebRequest https://github.com/Kitware/CMake/releases/download/v${cmake_ver}/cmake-${cmake_ver}-win64-x64.zip -OutFile build\cmake.zip
          Expand-Archive build\cmake.zip -DestinationPath build\cmake
#          Remove-Item –path build\cmake.zip
#          Add-Content -Path "$env:GITHUB_PATH" -Value "$((Get-Item .).FullName)\build\cmake\cmake-${cmake_ver}-win64-x64\bin"
#          Add-Content -Path "$env:GITHUB_ENV" -Value "$CMAKE_BUILD_PARALLEL_LEVEL = $((Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors * 8)"
      - name: Install Vulkan SDK
        run: powershell -noexit -File .\scripts\powershell\install-vulkan-sdk.ps1
      - name: Echo places
        run: echo $env:VULKAN_SDK ; echo $env:Path
        shell: powershell